version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php
    container_name: php8.0
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - /home/kai/Escritorio/Docker/Proyects/symfony-cicd:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/debug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    networks:
      - app-network

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: backend
    container_name: nginx1.15.12
    ports:
      - "4201:80"
    volumes:
      - /home/kai/Escritorio/Docker/Proyects/symfony-cicd:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

    networks:
      - app-network
    depends_on:
      - php

  mysql:
    image: mysql:5.7.10
    container_name: mysql.5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

    # volumes:
    #   - type: bind
    #     source: C:\Users\MichalPawel\Documents\Proyects\mysql5.7\
    #     target: /var/lib/mysql/

    # Si usas LINUX
    # COMENTA LAS LINEAS DEL VOLUMES DE ARRIBA Y DESCOMENTA LAS DE ABAJO
    volumes:
    - /home/kai/Escritorio/Docker/docker-data/project1:/var/lib/mysql

    ports:
      - "3316:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.21.0.0/16